### ISSUE TITLE
구조 개선: commit 시마다 전 액션 빌드되는 flow 수정

### ISSUE THREAD

**Issue by seunghyun-kevinkim-naver** [NaverPayDev/actions#38]
### 내용

- 현재 코드 수정시마다 변경 내용을 build된 dist 파일에 반영하기 위해 commit 시마다 전 액션을 빌드하고 있습니다
  - 변경이 생긴 액션은 모두 dist 파일이 변경되고 합쳐서 commit을 다시해야함
- 따라서 번거롭게 두번 작업해야합니다.
  - 1. commit 전에 전체 빌드를 돌리고 빌드 결과물을 합쳐서 commit한다
  - 2. commit을 하고, 빌드가 돌아 생성된 결과물을 따로 commit한다 (혹은 이전 commit을 취소하고 낑겨서 다시 commit한다)
- action 특성상 브랜치로 푸시하기 전까지 어짜피 로컬에서 테스트가 불가능하기 때문에 빌드 결과물을 PR 생성시 changeset 처럼 commit으로 자동으로 추가하면 한결 덜 번거로워질 것 같습니다.
- 액션별로 라벨을 만들고, 라벨이 붙은 액션만 빌드하게 해서 타 액션에 영향을 없애는 방안은 어떨지 함께 검토 필요

**Comment by 2-one-week** [comment]
@seunghyun-kevinkim-naver 님

> 변경이 생긴 액션은 모두 dist 파일이 변경되고 합쳐서 commit을 다시해야함

husky나 lefthook `pre-commit` 에서 `pnpm run build && git add .` 하면 될 듯 합니다?

**Comment by seunghyun-kevinkim-naver** [comment]
@2-one-week 님, commit시마다 전 액션 build를 다 돌리다보니 액션이 추가될수록 commit에 필요한 시간이 길어지고 있어서요

+) 현재 api 라이브러리를 다같이 쓰다보니 lib의 api 하나만 바뀌어도 전체 액션이 전부 빌드가 돌아야합니다 ㅎㅎ...
차라리 commit을 빨리 하고, ci가 돌면서 빌드 결과물이 생성되면 어떨까하여 의견 써보았습니다.

**Comment by yceffort-naver** [comment]
![image](https://github.com/NaverPayDev/actions/assets/158988311/d18c7131-9edb-4360-9e86-a96c65b9a528)
